### ISSUE TITLE
Add main page

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Support-Site#2]
Make the main page and add functionality to it.

**Tasks** 

- [x] Desing the main page
- [x] Build the main page structure 
- [x] Add the main functionality
