### ISSUE TITLE
Create Post Page

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Support-Site#4]
Add a page where users can post new questions. 

**Tasks:** 

- [x] Create a Post Page
- [x] Add Functionality to the post page.
- [x] Make the post button link to it on the main page.
