### ISSUE TITLE
Add support for environment variables.

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Support-Site#9]
Add support for environment variables in react for the api urls such as the support server and the auth server. 

**.env.production**
```
SUPPORT_SERVER_URL=http://api.supportsite.lifplaforms.com:8002
AUTH_SERVER_URL=http://auth.lifplatforms.com:8002
```

**.env.development**
```
SUPPORT_SERVER_URL=localhost:8003
AUTH_SERVER_URL=localhost:8002
```

**Tasks**
- [x] Create env files and commit them to public repo.
- [x] Add env variables to files.
- [x] Update site to use env variables.
